# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('past_explanation', models.ForeignKey(blank=True, db_constraint=False, default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, to='buggy.Explanation')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(db_index=True)),
                ('score', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='explanation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buggy.Question'),
        ),
        migrations.AddField(
            model_name='explanation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
